stages:
  - build
  - test

compile-go:
  image: golang:1.7
  stage: build
  script:
    # Loop through *.go, go build, if exit code is not 0, then exit 66
    - go get -u github.com/kardianos/govendor
    - govendor sync
    - go build

test-go:
  image: golang:1.7
  stage: test
  script:
    - go get -v
    - go test
