image: golang:1.7
before_script:
    - mkdir $HOME/go
    - export GOPATH=$HOME
    - go get github.com/kardianos/govendor
    - ls -la $HOME
    - ls -la $HOME/go
stages:
  - build
  - test

compile-go:
  stage: build
  script:
    - ls
    - ls $HOME/go
    - $HOME/bin/govendor sync
    - go build

test-go:
  stage: test
  script:
    - ~/go/govendor sync
    - go test
