compile-go-1.5:
  image: golang:1.5
  stage: build
  script:
    # Loop through *.go, go build, if exit code is not 0, then exit 66
    - go get -v -u
    - go build

compile-go-1.5:
  image: golang:1.5
  stage: test
  script:
    # Loop through *.go, go build, if exit code is not 0, then exit 66
    - go test